# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
  
jobs:
- job: BuildAngular
  displayName: Build Angular
  pool:
    name: 'Default'
  steps:
  - script: |
      cd terraman-ui
      npm install
    displayName: 'npm install'
    continueOnError: true
  - script: |
      cd terraman-ui
      npm run build:prod
    displayName: 'npm run build'
  - publish: $(System.DefaultWorkingDirectory)/terraman-ui
    artifact: angular
- job: BuildElectron
  displayName: Build Electron
  dependsOn: BuildAngular
  pool:
    name: 'ARM'
  steps:
  - download: current
    artifact: angular
  - script: |
      cd ../angular
      npm install
      electron-builder build --armv7l
