# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'ARM'

steps:
- script: |
    cd terraman-ui
    npm install
    npm run electron:build
  displayName: 'npm install and build'
