#!/usr/bin/env python3

import relay
import busio
import time
import board

i2c = busio.I2C(board.SCL, board.SDA)
relayController = relay.Relay()
relayController.turnOnChannel(0)
time.sleep(0.5)
relayController.turnOnChannel(1)
time.sleep(0.5)
relayController.turnOnChannel(2)
time.sleep(0.5)
relayController.turnOnChannel(3)
time.sleep(0.5)
relayController.turnOnChannel(4)
time.sleep(0.5)
relayController.turnOnChannel(5)
time.sleep(0.5)
relayController.turnOnChannel(6)
time.sleep(0.5)
relayController.turnOnChannel(7)
time.sleep(2)
relayController.turnOffChannel(0)
time.sleep(0.5)
relayController.turnOffChannel(1)
time.sleep(0.5)
relayController.turnOffChannel(2)
time.sleep(0.5)
relayController.turnOffChannel(3)
time.sleep(0.5)
relayController.turnOffChannel(4)
time.sleep(0.5)
relayController.turnOffChannel(5)
time.sleep(0.5)
relayController.turnOffChannel(6)
time.sleep(0.5)
relayController.turnOffChannel(7)
